# Generated by Django 3.0.4 on 2020-03-22 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_auto_20200314_1244'),
        ('auth', '0011_update_proxy_permissions'),
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='CustomGroup',
        ),
    ]
