# Generated by Django 3.0.4 on 2020-03-29 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listitem',
            old_name='text',
            new_name='name',
        ),
    ]
