# Generated by Django 3.0.4 on 2020-03-14 12:44

import auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', auth.models.UserManager()),
            ],
        ),
    ]
